# Generated by Django 2.2.2 on 2020-07-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название события')),
                ('date_start', models.DateTimeField(verbose_name='начало события')),
                ('date_stop', models.DateTimeField(blank=True, verbose_name='окончание события')),
                ('reminder', models.DurationField()),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
                'db_table': 'my_event',
            },
        ),
    ]
